# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  bkstrgname : 'BRG1'
  bkstrgacc : 'ncplbackendstorage'
  bkcontainer : 'merranbo'
  #bkfile : '2_2_Values.tfvars'

stages:
  - stage: Dev
    displayName: Deploy to Development
    variables:
      env: 'Dev'
      bkkey : 'dev.terraform.tfstate'
      varfile: 'A_Dev.tfvars'
    jobs:
      - deployment: DeployDev
        displayName: Deploy to Dev
        environment: 'Dev'
        continueOnError: false
        strategy:
          runOnce:
            deploy:
              steps:
                  - checkout: self
                  - task: TerraformInstaller@1
                    displayName: Terraform Install
                    inputs:
                      terraformVersion: 'latest'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Init
                    inputs:
                      provider: 'azurerm'
                      command: 'init'
                      backendServiceArm: 'Azure subscription 1(3f48112c-a56d-44e0-9a80-1ed5fbce3aac)'
                      backendAzureRmResourceGroupName: '$(bkstrgname)'
                      backendAzureRmStorageAccountName: '$(bkstrgacc)'
                      backendAzureRmContainerName: '$(bkcontainer)'
                      backendAzureRmKey: '$(bkkey)'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Validate
                    inputs:
                      provider: 'azurerm'
                      command: 'validate'
                  - task: Bash@3
                    displayName: Workspace Creation
                    inputs:
                      targetType: 'inline'
                      script: 'terraform workspace new $(env)'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Plan
                    inputs:
                      provider: 'azurerm' 
                      command: 'plan'
                      commandOptions: '-var-file="$(varfile)"'
                      environmentServiceNameAzureRM: 'Azure subscription 1(3f48112c-a56d-44e0-9a80-1ed5fbce3aac)'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Apply
                    inputs:
                      provider: 'azurerm'
                      command: 'apply'
                      commandOptions: '-var-file="$(varfile)"'
                      environmentServiceNameAzureRM: 'Azure subscription 1(3f48112c-a56d-44e0-9a80-1ed5fbce3aac)'

  - stage: Stage
    displayName: Deploy to Staging
    condition: succeeded ('Dev')
    dependsOn: Dev
    variables:
      env: 'Stage'
      bkkey : 'stage.terraform.tfstate'
      varfile: 'A_Stage.tfvars'
    jobs:
      - deployment: DeployStage
        displayName: Deploy to Staging
        environment: 'Stage'
        continueOnError: false
        strategy:
          runOnce:
            deploy:
              steps:
                  - checkout: self
                  - task: TerraformInstaller@1
                    displayName: Terraform Install
                    inputs:
                      terraformVersion: 'latest'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Init
                    inputs:
                      provider: 'azurerm'
                      command: 'init'
                      backendServiceArm: 'Azure subscription 1(3f48112c-a56d-44e0-9a80-1ed5fbce3aac)'
                      backendAzureRmResourceGroupName: '$(bkstrgname)'
                      backendAzureRmStorageAccountName: '$(bkstrgacc)'
                      backendAzureRmContainerName: '$(bkcontainer)'
                      backendAzureRmKey: '$(bkkey)'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Validate
                    inputs:
                      provider: 'azurerm'
                      command: 'validate'
                  - task: Bash@3
                    displayName: Workspace Creation
                    inputs:
                      targetType: 'inline'
                      script: 'terraform workspace new $(env)'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Plan
                    inputs:
                      provider: 'azurerm' 
                      command: 'plan'
                      commandOptions: '-var-file="$(varfile)"'
                      environmentServiceNameAzureRM: 'Azure subscription 1(3f48112c-a56d-44e0-9a80-1ed5fbce3aac)'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Apply
                    inputs:
                      provider: 'azurerm'
                      command: 'apply'
                      commandOptions: '-var-file="$(varfile)"'
                      environmentServiceNameAzureRM: 'Azure subscription 1(3f48112c-a56d-44e0-9a80-1ed5fbce3aac)'
                      
  - stage: Prod
    displayName: Deploy to Production
    condition: succeeded ('Stage')
    dependsOn: Stage
    variables:
      env: 'Prod'
      bkkey : 'prod.terraform.tfstate'
      varfile: 'A_Prod.tfvars'
    jobs:
      - deployment: DeployProd
        displayName: Deploy to Production
        environment: 'Prod'
        continueOnError: false
        strategy:
          runOnce:
            deploy:
              steps:
                  - checkout: self
                  - task: TerraformInstaller@1
                    displayName: Terraform Install
                    inputs:
                      terraformVersion: 'latest'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Init
                    inputs:
                      provider: 'azurerm'
                      command: 'init'
                      backendServiceArm: 'Azure subscription 1(3f48112c-a56d-44e0-9a80-1ed5fbce3aac)'
                      backendAzureRmResourceGroupName: '$(bkstrgname)'
                      backendAzureRmStorageAccountName: '$(bkstrgacc)'
                      backendAzureRmContainerName: '$(bkcontainer)'
                      backendAzureRmKey: '$(bkkey)'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Validate
                    inputs:
                      provider: 'azurerm'
                      command: 'validate'
                  - task: Bash@3
                    displayName: Workspace Creation
                    inputs:
                      targetType: 'inline'
                      script: 'terraform workspace new $(env)'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Plan
                    inputs:
                      provider: 'azurerm' 
                      command: 'plan'
                      commandOptions: '-var-file="$(varfile)"'
                      environmentServiceNameAzureRM: 'Azure subscription 1(3f48112c-a56d-44e0-9a80-1ed5fbce3aac)'
                  - task: TerraformTaskV4@4
                    displayName: Terraform Apply
                    inputs:
                      provider: 'azurerm'
                      command: 'apply'
                      commandOptions: '-var-file="$(varfile)"'
                      environmentServiceNameAzureRM: 'Azure subscription 1(3f48112c-a56d-44e0-9a80-1ed5fbce3aac)'